parameters:
#    acme_generator.example.class: Acme\GeneratorBundle\Example

services:
#    acme_generator.example:
#        class: %acme_generator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
